import { ThemeColors } from "../../types/types";

export const themes: Record<string, ThemeColors> = {
    gruvbox: {
        name: "Gruvbox",
        bg: "#282828",
        surface: "#3c3836",
        text: "#ebdbb2",
        textMuted: "#a89984",
        accent: "#fe8019",
    },
    "gruvbox-material": {
        name: "Gruvbox Material",
        bg: "#202020",
        surface: "#2a2a2a",
        text: "#dfdfc2",
        textMuted: "#a89984",
        accent: "#ea6962",
    },
    "tokyo-night": {
        name: "Tokyo Night",
        bg: "#1a1b26",
        surface: "#24283b",
        text: "#a9b1d6",
        textMuted: "#565f89",
        accent: "#7aa2f7",
    },
    "catppuccin-latte": {
        name: "Catppuccin Latte",
        bg: "#eff1f5",
        surface: "#e6e9ef",
        text: "#4c4f69",
        textMuted: "#8c8fa1",
        accent: "#8839ef",
    },
    "catppuccin-frappe": {
        name: "Catppuccin Frappé",
        bg: "#303446",
        surface: "#292c3c",
        text: "#c6d0f5",
        textMuted: "#838ba7",
        accent: "#ca9ee6",
    },
    "catppuccin-macchiato": {
        name: "Catppuccin Macchiato",
        bg: "#24273a",
        surface: "#1e2030",
        text: "#cad3f5",
        textMuted: "#8087a2",
        accent: "#c6a0f6",
    },
    "catppuccin-mocha": {
        name: "Catppuccin Mocha",
        bg: "#1e1e2e",
        surface: "#181825",
        text: "#cdd6f4",
        textMuted: "#7f849c",
        accent: "#cba6f7",
    },
    everforest: {
        name: "Everforest",
        bg: "#2d353b",
        surface: "#343f44",
        text: "#d3c6aa",
        textMuted: "#859289",
        accent: "#a7c080",
    },
    kanagawa: {
        name: "Kanagawa",
        bg: "#1f1f28",
        surface: "#2a2a37",
        text: "#dcd7ba",
        textMuted: "#727169",
        accent: "#ff5d62",
    },
    nightfox: {
        name: "Nightfox",
        bg: "#192330",
        surface: "#212e3f",
        text: "#cdcecf",
        textMuted: "#71839b",
        accent: "#719cd6",
    },
    osaka: {
        name: "Tokyo Osaka",
        bg: "#16161e",
        surface: "#1f2335",
        text: "#c0caf5",
        textMuted: "#414868",
        accent: "#ff9e64",
    },
    "rose-pine": {
        name: "Rosé Pine",
        bg: "#191724",
        surface: "#1f1d2e",
        text: "#e0def4",
        textMuted: "#908caa",
        accent: "#ebbcba",
    },
    nordic: {
        name: "Nordic",
        bg: "#2e3440",
        surface: "#3b4252",
        text: "#d8dee9",
        textMuted: "#4c566a",
        accent: "#88c0d0",
    },
};
